name: Publish Image to GHCR

on:
  workflow_dispatch:

env:
  CR: ghcr.io/${{ github.repository_owner }}
  VERSION: v2

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hardened Images Registry
        uses: docker/login-action@v2
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Base Dev Environment
        uses: docker/build-push-action@v4
        with:
          context: ./base
          push: true
          tags: ${{ env.CR }}/dev-node:${{ env.VERSION }}

      - name: Build Node.js with Playwright dependencies Dev Environment
        uses: docker/build-push-action@v4
        with:
          context: ./playwright
          push: true
          tags: ${{ env.CR }}/dev-playwright:${{ env.VERSION }}

      - name: Build Firebase Dev Environment
        uses: docker/build-push-action@v4
        with:
          context: ./firebase
          push: true
          tags: ${{ env.CR }}/dev-firebase:${{ env.VERSION }}

      - name: Build Rust Dev Environment
        uses: docker/build-push-action@v4
        with:
          context: ./rust
          push: true
          tags: ${{ env.CR }}/dev-rust:${{ env.VERSION }}
